name: Deploy
env:
  CI: true
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run test -- --watch=false --browsers=ChromeHeadless
      #- name: Github pages
        #uses: sterlingwes/gh-pages-deploy-action@v1.1
        #with:
          #access-token: ${{ secrets.ACCESS_TOKEN }}
          #source-directory: dist/ngx-form-schema
          #build-command: npm run build-demo
      - name: Tag
        run: ./tag-version.sh
      - run: npm run build:lib
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
